services:
  web-litespeed:
    build: ./conf/litespeed
    restart: unless-stopped
    ports:
      - "8087:80"
      - "7080:7080"
      - "8443:443"
      - "8088:8088"
    volumes:
      - ./src/php-app:/var/www/vhosts/localhost
    environment:
      - APP_ENV=dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
